// generated 2004/4/17 21:33:30 EDT by pug@resmiranda.berthall.com.(none)
// using glademm V2.0.0.1
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- imfavorites.glade --header-suffix .h
// for gtk 2.2.4 and gtkmm 2.2.0
//
// Please modify the corresponding derived classes in ./src/doneDialog.h and./src/doneDialog.cc

#ifndef _DONEDIALOG_GLADE_H
#  define _DONEDIALOG_GLADE_H


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/label.h>

class doneDialog_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
protected:
        class Gtk::Dialog *doneDialog;
public:
        class Gtk::Label *doneDialogText;
protected:
        
        doneDialog_glade();
        
        ~doneDialog_glade();
private:
        virtual void on_doneDialog_close_clicked() = 0;
        virtual void on_doneDialog_ok_clicked() = 0;
};
#endif
