// generated 2004/3/30 10:08:39 EST by pug@resmiranda.berthall.com.(none)
// using glademm V2.0.0.1
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- imfavorites.glade --header-suffix .h
// for gtk 2.2.4 and gtkmm 2.2.0
//
// Please modify the corresponding derived classes in ./src/fileSelection.h and./src/fileSelection.cc

#ifndef _FILESELECTION_GLADE_H
#  define _FILESELECTION_GLADE_H


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/fileselection.h>

class fileSelection_glade : public Gtk::FileSelection
{  
        
        GlademmData *gmm_data;
protected:
        class Gtk::FileSelection *fileSelection;
        
        fileSelection_glade();
        
        ~fileSelection_glade();
private:
        virtual void on_fileSelection_close() = 0;
};
#endif
