// generated 2004/4/23 14:36:40 EDT by pug@resmiranda.berthall.com.(none)
// using glademm V2.0.0.1
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- imfavorites.glade --header-suffix .h
// for gtk 2.2.4 and gtkmm 2.2.0
//
// Please modify the corresponding derived classes in ./src/mainWindow.h and./src/mainWindow.cc

#ifndef _MAINWINDOW_GLADE_H
#  define _MAINWINDOW_GLADE_H


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/tooltips.h>
#include <gtkmm/image.h>
#include <gtkmm/radiobutton.h>
#include <gtkmm/spinbutton.h>
#include <gtkmm/entry.h>
#include <gtkmm/button.h>
#include <gtkmm/checkbutton.h>
#include <gtkmm/progressbar.h>

class mainWindow_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
protected:
        Gtk::Tooltips _tooltips;
        class Gtk::Window *mainWindow;
        class Gtk::Image *image1;
        class Gtk::RadioButton *sizeOtherRadio;
        class Gtk::RadioButton *limitSizeRadio;
        class Gtk::RadioButton *sizeCDRadio;
        class Gtk::RadioButton *sizeCD2Radio;
        class Gtk::RadioButton *sizeDVDRadio;
        class Gtk::RadioButton *limitNumberRadio;
        class Gtk::SpinButton *numSongsSpinButton;
        class Gtk::Entry *directoryEntry;
        class Gtk::SpinButton *otherSizeSpinButton;
        class Gtk::Button *browseButton;
        class Gtk::RadioButton *limitLengthRadio;
        class Gtk::SpinButton *minutesSpinButton;
        class Gtk::SpinButton *secondsSpinButton;
        class Gtk::CheckButton *cramCheckBox;
        class Gtk::ProgressBar *progressbar1;
        
        mainWindow_glade();
        
        ~mainWindow_glade();
private:
        virtual void on_sizeOtherRadio_toggled() = 0;
        virtual void on_limitRadio_toggled() = 0;
        virtual void on_SizeCDRadio_toggled() = 0;
        virtual void on_sizeCD2Radio_toggled() = 0;
        virtual void on_sizeDVDRadio_toggled() = 0;
        virtual void on_limitNumberRadio_toggled() = 0;
        virtual void on_numSongsSpinButton_changed() = 0;
        virtual void on_browseButton_activate() = 0;
        virtual void on_limitLengthRadio_toggled() = 0;
        virtual void on_cramCheckBox_toggled() = 0;
        virtual void on_startButton_activate() = 0;
};
#endif
